### ISSUE TITLE
some fbx can not dispaly

### ISSUE THREAD

**Issue by FourTest** [EYHN/space-thumbnails#9]
大佬有2个问题:
1.fbx纹理文件不能显示
2.有些fbx生成缩略图失败

这个是fbx-sdk自带的fbx文件,不能生成缩略图
https://github.com/EYHN/space-thumbnails/files/9008133/humanoid.zip

控制台显示:

thread 'main' panicked at 'called Option::unwrap() on a None value', crates\cli\src\main.rs:58:48
note: run with RUST_BACKTRACE=1 environment variable to display a backtrace

**Comment by FourTest** [comment]
the fbxfile

https://github.com/EYHN/space-thumbnails/files/9008133/humanoid.zip

**Comment by FourTest** [comment]
the cmd show:

thread 'main' panicked at 'called Option::unwrap() on a None value', crates\cli\src\main.rs:58:48
note: run with RUST_BACKTRACE=1 environment variable to display a backtrace

**Comment by EYHN** [comment]
The link you submitted does not contain any file.
It looks like the issue doesn't seem to be related to the file.

Please tell me the command you used.

**Comment by FourTest** [comment]
space-thumbnails-cli.exe  -i e:/humanoid.fbx  e:/humanoid.png

**Comment by FourTest** [comment]
https://github.com/EYHN/space-thumbnails/files/9008133/humanoid.zip
